-
  name: lamp stack
  hosts: lamp_web
  var:
    db_name: employee_db
    db_user: db_user
    db_password: Passw0rd
  tasks:
    - name: Install all required dependencies
      yum: name='{{ item }}' state=present
      with_items:
        - epel-release
        - python
        - python-pip

    - name: Download repository
      get_url:
      url: http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
      dest: /tmp

    - name: Install MySQL Community Repo
      command: /usr/bin/rpm -ivh /tmp/mysql-community-release-el7-7.noarch.rpm

    - name: Install and Configure Database
      yum: name={{ item }} state=installed
      with_items:
        - udate
        - mysql-server
        - mysql-client

    - name: Start MySql service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create database
      mysql_db: {{ db_name}} state=present

    - name: Create database users
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: '*.*:ALL'
        state: present

    - name: Install Python Flask dependency
      pip: name={{ item }} state=present
      with_items:
        - flask
        - flask-mysql

    - name: Copy source code
      copy: src=app.py dest=/opt/app.py

    - name: Start webserver
      shell: FLASK_APP=app.py flask run --host=0.0.0.0 &
