
    - name: 'add user'
      user:
        name: "{{ ssh_user }}"
        password: "{{ ssh_pass | password_hash('sha512') }}"
        comment: ansible user
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        status: present


    - copy:
        content: "ansible ALL=(ALL)   NOPASSWD:ALL"
        dest: "/etc/sudoers.d/ansible"
